# Example: Complete setup with CI, release-plz, and releases
# This shows how to use the GitHub Action for a complete Rust project setup

# File: .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: loonghao/rust-actions-toolkit@v3
        with:
          command: ci
          rust-toolchain: stable

  # Optional: Code coverage (only on PRs to avoid noise)
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: loonghao/rust-actions-toolkit@v3
        with:
          command: setup
          rust-toolchain: stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info

---
# File: .github/workflows/release-plz.yml
name: Release-plz
on:
  push:
    branches: [main]

jobs:
  release:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-release-plz.yml@v3
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Optional: Enhanced GitHub PAT for cross-workflow triggers
      RELEASE_PLZ_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}

---
# File: .github/workflows/release.yml
name: Release
on:
  push:
    tags: ["v*"]

jobs:
  # Option 1: Use reusable workflow (traditional approach)
  release-reusable:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-release.yml@v3
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Option 2: Use GitHub Action for custom matrix (updated)
  release-custom:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # 2025 optimized platform strategy (Tier 1: Core platforms)
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-13
            target: aarch64-apple-darwin
          - os: windows-2022
            target: x86_64-pc-windows-msvc
          # Tier 2: Important platforms
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - uses: loonghao/rust-actions-toolkit@v3
        with:
          command: release
          target: ${{ matrix.target }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          binary-name: ""  # Auto-detect from Cargo.toml
          enable-python-wheels: true  # Enable if you have pyproject.toml

  # Option 3: Use smart-release action (recommended - zero config)
  release-smart:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Core platforms for smart-release demo
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: macos-13
            target: x86_64-apple-darwin
          - os: windows-2022
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      # That's it! Everything else is automatic ✨
      - uses: loonghao/rust-actions-toolkit/actions/smart-release@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}
