# turbo-cdn Release Configuration - rust-actions-toolkit v4
# Enhanced multi-platform releases using native GitHub runners

name: Release
on:
  push:
    tags: ['v*']

jobs:
  release:
    uses: loonghao/rust-actions-toolkit/.github/workflows/enhanced-release.yml@v4
    with:
      binary-name: "turbo-cdn"
      platforms: "linux,macos,windows"

# This provides:
# ✅ Multi-platform native builds:
#   - Linux x86_64 (ubuntu-22.04)
#   - macOS x86_64 (macos-13) 
#   - macOS aarch64 (macos-14, Apple Silicon)
#   - Windows x86_64 (windows-2022)
# ✅ Automatic GitHub release creation
# ✅ Platform-specific archives (tar.gz for Unix, zip for Windows)
# ✅ Fast builds using native runners
# ✅ No cross-compilation complexity
# ✅ No proc-macro issues (serde, async-trait, thiserror, clap all work)
# ✅ No Docker permission problems
# ✅ Reliable, production-ready releases

# Optional: Customize platforms
# platforms: "linux,macos"        # Only Linux and macOS
# platforms: "linux"              # Only Linux
# platforms: "linux,windows"      # Linux and Windows only

# Optional: Custom binary name detection
# If not specified, automatically detects from Cargo.toml
