# Release-plz configuration for rust-actions-toolkit
#
# This is a GitHub Actions toolkit, not a Rust crate, so we:
# - Don't publish to crates.io (no Rust packages)
# - Focus on GitHub releases for Action versioning
# - Use semantic versioning for Action compatibility
#
# Workflow:
# 1. release-plz creates tag (v1.0.0) and GitHub release with changelog
# 2. Tag triggers publish-action.yml workflow for GitHub Marketplace
# 3. Major version tag (v1) is created/updated automatically
# 4. Users can reference @v1, @v1.0.0, etc.

[workspace]
# Enable automatic changelog generation
changelog_update = true
# Disable GitHub releases at workspace level (handled by package level)
git_release_enable = false
# Enable automatic tag creation (triggers publish-action.yml)
git_tag_enable = true
# Disable crates.io publishing (this is not a Rust crate)
release = false

# Changelog configuration
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

# GitHub Actions toolkit configuration
[[package]]
# This represents the GitHub Action itself (not a Rust package)
name = "rust-actions-toolkit"
# Enable changelog updates
changelog_update = true
# Enable GitHub releases for Action versioning
git_release_enable = true
# Disable crates.io publishing (this is not a Rust crate)
release = false
# Standard tag format for GitHub Actions - with 'v' prefix
git_tag_name = "v{{version}}"
# Allow major version bumps for breaking changes
allow_dirty = false
# Ensure proper semantic versioning for Action compatibility
semver_check = true
# Create published releases immediately
git_release_draft = false
# Custom release body template for GitHub Actions
git_release_body = """
## 🚀 What's Changed

{{changelog}}

## 📦 Usage

### GitHub Action (Recommended)
```yaml
- uses: loonghao/rust-actions-toolkit@{{version}}
  with:
    command: ci
```

### Reusable Workflows
```yaml
uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-ci.yml@{{version}}
```

### Version References
```yaml
- uses: loonghao/rust-actions-toolkit@{{version}}  # Specific version
- uses: loonghao/rust-actions-toolkit@v{{major}}   # Major version
- uses: loonghao/rust-actions-toolkit@main         # Latest (not recommended for production)
```

## 🔗 Links
- [Documentation](https://github.com/loonghao/rust-actions-toolkit/blob/{{version}}/README.md)
- [Usage Guide](https://github.com/loonghao/rust-actions-toolkit/blob/{{version}}/USAGE.md)
- [Examples](https://github.com/loonghao/rust-actions-toolkit/tree/{{version}}/examples)
- [Marketplace](https://github.com/marketplace/actions/rust-actions-toolkit)

**Full Changelog**: https://github.com/loonghao/rust-actions-toolkit/compare/{{previous_tag}}...{{version}}
"""


