# Example: Using reusable release workflow
# Place this file at .github/workflows/release.yml in your project

name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-release.yml@main
    with:
      # Optional: Customize Rust toolchain
      rust-toolchain: stable
      # Optional: Specify binary name (auto-detected if not provided)
      binary-name: ""
      # Optional: Enable/disable Python wheels
      enable-python-wheels: true
      # Optional: Customize target platforms (JSON array)
      target-platforms: |
        [
          {"target": "x86_64-unknown-linux-gnu", "os": "ubuntu-22.04"},
          {"target": "x86_64-unknown-linux-musl", "os": "ubuntu-22.04"},
          {"target": "aarch64-unknown-linux-gnu", "os": "ubuntu-22.04"},
          {"target": "x86_64-apple-darwin", "os": "macos-13"},
          {"target": "aarch64-apple-darwin", "os": "macos-13"},
          {"target": "x86_64-pc-windows-msvc", "os": "windows-2022"}
        ]
    secrets:
      # Required: For GitHub release uploads
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
