# Example configuration for a pure Rust library crate
# This is suitable for projects that only publish to crates.io without binaries
# Place this file at the root of your project as "release-plz.toml"

[workspace]
# Enable automatic changelog generation
changelog_update = true
# Disable GitHub releases at workspace level (handled by package level)
git_release_enable = false
# Enable automatic tag creation (triggers release workflows)
git_tag_enable = true
# Enable processing for releases
release = true

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

[[package]]
name = "my-awesome-lib"  # CHANGE THIS: Replace with your actual library name
changelog_update = true
git_release_enable = true
release = true  # Enable crates.io publishing
git_tag_name = "v{{version}}"
allow_dirty = false
semver_check = true
git_release_draft = false
git_release_body = """
## 🚀 What's Changed

{{changelog}}

## 📦 Installation

### Using Cargo
```bash
cargo add {{package}}
```

### From crates.io
```bash
cargo install {{package}}
```

## 🔗 Links
- [Documentation](https://docs.rs/{{package}})
- [Crates.io](https://crates.io/crates/{{package}})
- [Examples](https://github.com/{{owner}}/{{package}}/tree/main/examples)
- [Changelog](https://github.com/{{owner}}/{{package}}/blob/main/CHANGELOG.md)

**Full Changelog**: https://github.com/{{owner}}/{{package}}/compare/{{previous_tag}}...{{version}}
"""

# Required secrets for this configuration:
# - CARGO_REGISTRY_TOKEN: Your crates.io API token
# - GITHUB_TOKEN: Automatically provided by GitHub
# - RELEASE_PLZ_TOKEN: Optional GitHub PAT for enhanced features
