# Enhanced Release Configuration Example
# This example shows how to use the improved rust-actions-toolkit
# with CI consistency verification

name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write  # For uploading release assets

jobs:
  release:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-release.yml@v2.3.2
    with:
      binary-name: "my-app"  # Replace with your binary name
      rust-toolchain: stable
      enable-python-wheels: false
      verify-ci-consistency: true  # New: Verify CI consistency

      # Target platform configuration - should match release-target-platforms in ci.yml
      # Optimized platform list based on 2025 mainstream Rust project best practices
      target-platforms: |
        [
          {"target": "x86_64-unknown-linux-gnu", "os": "ubuntu-22.04", "priority": "high"},
          {"target": "x86_64-apple-darwin", "os": "macos-13", "priority": "high"},
          {"target": "aarch64-apple-darwin", "os": "macos-13", "priority": "high"},
          {"target": "x86_64-pc-windows-msvc", "os": "windows-2022", "priority": "high"},
          {"target": "aarch64-unknown-linux-gnu", "os": "ubuntu-22.04", "priority": "medium"},
          {"target": "x86_64-unknown-linux-musl", "os": "ubuntu-22.04", "priority": "medium"},
          {"target": "aarch64-unknown-linux-musl", "os": "ubuntu-22.04", "priority": "medium"},
          {"target": "x86_64-pc-windows-gnu", "os": "ubuntu-22.04", "priority": "low"}
        ]
    secrets: inherit
