# Comparison of different release approaches
# This file shows three different ways to set up releases with rust-actions-toolkit

name: Release Comparison

on:
  push:
    tags: ['v*']

jobs:
  # Method 1: Smart Release (Recommended - Zero Config)
  # ✅ Minimal configuration (3 lines)
  # ✅ Automatic project detection
  # ✅ Optimal defaults
  # ✅ Custom release notes template support
  smart-release:
    name: Smart Release (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # 2025 optimized core platforms
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-22.04 }
          - { target: x86_64-apple-darwin, os: macos-13 }
          - { target: x86_64-pc-windows-msvc, os: windows-2022 }
    steps:
      - uses: actions/checkout@v4
      
      # That's it! Everything else is automatic ✨
      - uses: loonghao/rust-actions-toolkit/actions/smart-release@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}

  # Method 2: Upload Release Artifacts (Medium Control)
  # 🔧 More control over build and upload process
  # 🔧 Separate build and upload steps
  # 🔧 Custom artifact handling
  upload-artifacts:
    name: Upload Artifacts (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: x86_64-pc-windows-msvc, os: windows-2022 }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-22.04 }
    steps:
      - uses: actions/checkout@v4
      
      # Step 1: Build with main action
      - uses: loonghao/rust-actions-toolkit@v3
        with:
          command: release
          target: ${{ matrix.target }}
          enable-python-wheels: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Upload with specialized action
      - uses: loonghao/rust-actions-toolkit/actions/upload-release-artifacts@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          binary-path: target/${{ matrix.target }}/release/
          wheel-path: target/wheels/
          create-archives: true

  # Method 3: Main Action (Full Control)
  # ⚙️ Maximum flexibility
  # ⚙️ Custom configuration for each step
  # ⚙️ Manual artifact handling
  main-action:
    name: Main Action (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: x86_64-pc-windows-msvc, os: windows-2022 }
    steps:
      - uses: actions/checkout@v4
      
      # Full control over every aspect
      - uses: loonghao/rust-actions-toolkit@v3
        with:
          command: release
          target: ${{ matrix.target }}
          binary-name: my-app
          rust-toolchain: stable
          enable-python-wheels: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      # Manual upload using external action
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ matrix.target }}/release/my-app*
            target/wheels/*.whl
          token: ${{ secrets.GITHUB_TOKEN }}

# Comparison Summary:
#
# | Method | Config Lines | Maintenance | Flexibility | Use Case |
# |--------|-------------|-------------|-------------|----------|
# | Smart Release | 3-5 | Low | Medium | Most projects |
# | Upload Artifacts | 10-15 | Medium | High | Custom needs |
# | Main Action | 20+ | High | Maximum | Complex setups |
#
# Recommendations:
# - Use Smart Release for 90% of projects
# - Use Upload Artifacts when you need custom build logic
# - Use Main Action when you need maximum control
#
# Platform Support (v3 - 2025 Optimized):
# Tier 1 (Core): x86_64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin, x86_64-pc-windows-msvc
# Tier 2 (Important): aarch64-unknown-linux-gnu, x86_64-unknown-linux-musl, aarch64-unknown-linux-musl
# Tier 3 (Optional): x86_64-pc-windows-gnu (zero-dependency builds)
# Removed: i686-pc-windows-gnu (32-bit Windows deprecated)
