# Release Configuration for Consistency Testing
# This configuration must match the CI targets exactly

name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write  # For uploading release assets

jobs:
  release:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-release.yml@v2.5.2
    with:
      binary-name: "my-app"  # Replace with your binary name
      rust-toolchain: stable
      enable-python-wheels: false
      
      # 🎯 KEY: Enable CI consistency verification
      verify-ci-consistency: true
      
      # 🎯 KEY: Use EXACTLY the same targets as ci.yml
      # This ensures consistency between CI and Release
      target-platforms: |
        [
          {"target": "x86_64-pc-windows-gnu", "os": "ubuntu-22.04"},
          {"target": "i686-pc-windows-gnu", "os": "ubuntu-22.04"},
          {"target": "x86_64-unknown-linux-musl", "os": "ubuntu-22.04"},
          {"target": "aarch64-unknown-linux-musl", "os": "ubuntu-22.04"},
          {"target": "x86_64-unknown-linux-gnu", "os": "ubuntu-22.04"},
          {"target": "aarch64-unknown-linux-gnu", "os": "ubuntu-22.04"},
          {"target": "x86_64-apple-darwin", "os": "macos-13"},
          {"target": "aarch64-apple-darwin", "os": "macos-13"}
        ]
    secrets: inherit
